define: &exp_name Fine tuning the whole model without freezing any layers
define: &runs runs/detect/
define: &best_path

artifacts_root: 
  artifacts

data_ingestions:
    root_dir: artifacts/data_ingestion
    source_dir: Raw_data/ts/ts
    train_images: artifacts/data_ingestion/images/train
    train_labels: artifacts/data_ingestion/labels/train
    test_images: artifacts/data_ingestion/images/test
    test_labels: artifacts/data_ingestion/labels/test
    val_images: artifacts/data_ingestion/images/val
    val_labels: artifacts/data_ingestion/labels/val

Training:
    experiment_name: 

evaluation:
    runs: runs/detect
    exp_name: Fine tuning the whole model without freezing any layers
    best: weights/best.pt



